######################## default configuration ####################
baseURL = "https://example.com"
languageCode = "en-us"
title = "Page Title"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""
pygmentsUseClasses=true

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "plugins/fontawesome/css/all.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 1


  # footer menu
  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Site description"
author = "author name"
# Google Analitycs
googleAnalyticsID = ""
# Contact Information
email = "admin@example.com"
location = "some location"
# copyright
copyright = ""

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################# social site ########################

[[params.social]]
title = "twitch"
icon = "fab fa-twitch" # themify icon : https://themify.me/themify-icons
link = "https://www.twitch.tv/"

[[params.social]]
title = "twitter"
icon = "ti-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/"

[[params.social]]
title = "youtube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/"
